var GAME_LEVELS = [
  /*["                                                               y yy   yyy       ",
   "                              yy                                yy yyyyyyy      ",
   "                       o o o  yy                            yy   vyyyyy y y     ",
   "                       ooooo                                  y      !  !       ",
   "                       ooooo y   y           yyy  y                  !  |       ",
   "       oooo         yyyyyyyyyy             yyyyyy yyy                           ",
   "       oooo        y           y               yyyy          yy   y       |     ",
   "      yy yyy                yy y              !                y  y             ",
   "    yyyyyyyyyy  y     y  o  y  yy                         yy  xxooxx       ooo  ",
   "      yyyyy y y  yyyo    y    oy                 y       y    xxooxx       ooo  ",
   "         v        yyyo o   o o y              y          y    xxooxxxxxxxxxxxx  ",
   "       v         y   y y y y yy yy       yy                   xxooxxxxxxxxxxxx  ",
   "              y       ! ! !             yyyy            y     xx ooo    ooo xx  ",
   "                      ! v ! y          yyyy y          y      xx o o    o o xx  ",
   "                o         !  y    y       !  y!yy!y           xx ooo    ooo xx  ",
   "             xxxoxxx          y               yyyy!           xxxxxxxooxxxxxxx  ",
   "             x     x         xxooxx!!!!!x !   yy  !           xx ooo    ooo xx  ",
   "             x     x         xx yxxxxxxxx         !           xx ooo    ooo xx  ",
   "           xxx     x         xx        xx    !                xxooxxxxxxxxxxxx  ",
   "             x     x         xx        xx         !           xx ooo    ooo xx  ",
   "             x     o         oxxxx   ooxx  !                  xx o o    o o xx  ",
   "  xxxxx      x     o   o o   o        xxx                     oo ooo    ooo xx  ",
   "  xxxxx   xxxx@ t  o  x   x  o         xx    !    !         y oo           kxx  ",
   "  xxxxx      xxxxxxx  x!!!x  xxxxxxx!!!xx                    yxxxxxxxxxxxxxxxx  "],
  ["                                                                  xxxxxxx                                         ",
   "                                                               xxxx     xxxx                                      ",
   "                                                              xx           xx                                     ",
   "                                                             xx             xx                                    ",
   "                                                             x                                                    ",
   "                                                             x     o   o                                          ",
   "                                                             x                                                    ",
   "                                                             x     x   x                                          ",
   "                                                             xx  |   |   |  xx                                    ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                          yy                                                                                      ",
   "                         yyyy                                                                                     ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                  yy                                                                                              ",
   "                  yyyy                                                                                            ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                           yy                                                                                     ",
   "                         yyyy                                                                                     ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                   yy                                                                                             ",
   "                  yyyy                                                                                            ",
   "                                                                                                                  ",
   "      @                                                                                                           ",
   "  xxxxxxxx       x     x                                                                                          ",
   "xxxxxxxxxxxxxxxxxx!!!!!!!!!!!                            x                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],*/
  ["yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "y                   oooooo  oo  oo   oooo   oo   oo  oo  oo    oo    oo    oooo    oo    oo                  y",
   "y                   oooooo  oo  ooy oooooo yooo  ooy oo oo  y   oo  oo   yoo  oo   oo    oo                  y",
   "y                     oo    oooooo  oo  oo  oooo oo  oooo  yyy   oooo    oo   yoo  oo    oo                  y",
   "y                  yy oo    oooooo  oooooo  oo oooo  oooo         oo  yy oo  yyoo  oo yy oo                  y",
   "y                 yyyyoo y  oo  oo yoo  ooy oo  ooo yoo oo    y   oo yyyy oo  oo    oo  oo                   y",
   "y                y   yooy y oo  ooyyoo  ooyyoo   ooyyoo  oo  yyy  oo       oooo  yy  oooo                    y",
   "y                                                                                                            y",
   "y x      t                                                                                                   y",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy yy",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy yy",
   " yyyy   yyyyy  yyyyyy    yyyyy     yyyyyyyyy   yyyy   yyyyy  yyyyyy    yyyyy     yyyyyyyyy                  yy",
   "             oooooo    oooo    oooooo     oooooo  oo       oooo   oo    oo  oo  oo   oo   oooooo            yy",
   "             oooooo   oo  oo   oo   oo    oo  oo  oo      oooooo   oo  oo   oo  ooo  oo  ooooooo            yy",
   "             oo      oo    oo  ooooooo    oooooo  oo    y oo  oo    oooo    oo  oooo oo  oo                 yy",
   "             oooo    oo    oo  oooooo  yy oooo    oo    yyoooooo     oo     oo  oo oooo  ooyyoooo           yy",
   "             oooo     oo  oo   oo   oo    oo  yy  oooooo  oo  oo     oo     oo  oo  ooo  oooooooo   yy      yy",
   "             oo        oooo    oo yyoo    oo  yyy oooooo  ooyyoo     oo yy  oo  oo y oo  oooooooy  yyy      yy",
   "                                                  yy            yy          yyyy  yyyy    yyyy            y@yy",
   "                                                                y    yy      yy yy         yy             yyyy",
   "                                                                                                           yyy",
   "                                                                                                            yy",
   "                                                                                                            yy",
   "                                                                                                            yy",
   "                                                                                                            yy",
   "                                                                                                            yy",
   "                                                                                                            yy",
   "                                                                                                            yy",
   "                                                                                                            yy",
   "                                                                                                            yy",
   "                                                                                                            yy",
   "                                                                                                            yy",
   "                                                                                                          k yy",
   "                                                                                                            yy"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
